### ISSUE TITLE
Whitelist Price not updating correctly

### ISSUE THREAD

**Issue by therealdaryl** [tonyboylehub/candymachine-v2-boiler-mint-site-noFLP#10]
I've customized the boilerplate and it fits my needs pretty well. However, I noticed the price for the whitelist or presale is not reflecting correctly. My public sale is 0.5 sol, and whitelist price is 0.4 sol. The entire whitelisting pricing and token reduction etc. works perfectly fine, but the display is not showing the correct value. During the whitelist it shows 0.5 sol (Even though only 0.4 is deducted). I looked into the tsx files and compared it to the original candy machine and tried to recreate it but unfortunately I am not good with react or typescript.

Based on the pull request #6, it solved my issue.

**Comment by seuaCoder** [comment]
I have the same issue
