### ISSUE TITLE
I want yo mint more then one nft in one go

### ISSUE THREAD

**Issue by rupesh-systango** [tonyboylehub/candymachine-v2-boiler-mint-site-noFLP#3]
I want to mint more then one nft when i will click mint button who can i do that

**Comment by tonyboylehub** [comment]
no one can yet I don't think. Candymachine doesn't support grouping into a single transaction when I spoke to the devs tonight. So it needs to make multiple transactions.

That's not a limitation of my UI but a limitation of Candymachine currently.
