### ISSUE TITLE
yarn build does not set links correctly and wallet does not connect

### ISSUE THREAD

**Issue by systemtechs** [tonyboylehub/candymachine-v2-boiler-mint-site-noFLP#5]
1. the href's for the locations do not build correctly for the production version. 
2. 2. When clicking connect wallet nothing happens. Again possible location issue

**Comment by tonyboylehub** [comment]
Works fine for all the deployments I done for people yesterday, and just deployed another one 20 mins ago with the same build.

**Comment by systemtechs** [comment]
I was trying to update this ticket to advise that it is no longer an issue, so thanks for getting back to me.
