### ISSUE TITLE
Failed to construct URL: Invalid URL

### ISSUE THREAD

**Issue by ekrocks21** [tonyboylehub/candymachine-v2-boiler-mint-site-noFLP#8]
After deploying on aws I am receiving the following error when trying to access the url

Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at new t (connection.ts:2075:15)
    at Module.301 (App.tsx:51:20)
    at u ((index):1:1135)
    at r ((index):1:1004)
    at Array.t [as push] ((index):1:867)
    at main.4c013541.chunk.js:1:125

Any ideas?

**Comment by tonyboylehub** [comment]
You haven't filled out your envirmoment variables somewhere on the AWS side of things. By default .env files are not uploaded to github.

**Comment by ekrocks21** [comment]
Thank you. This has been resolved via the approach above.
